USE health_data; 

CREATE TABLE brfss_clean (
  SEQNO VARCHAR(20),
  _STATE VARCHAR(5),
  SEXVAR VARCHAR(5),
  _AGEG5YR VARCHAR(10),
  WTKG3 VARCHAR(10),
  HTM4 VARCHAR(10),
  _IMPRACE VARCHAR(10),
  _EDUCAG VARCHAR(10),
  EMPLOY1 VARCHAR(10),
  _INCOMG1 VARCHAR(10),
  GENHLTH VARCHAR(10),
  PHYSHLTH VARCHAR(10),
  MENTHLTH VARCHAR(10),
  MEDCOST1 VARCHAR(10),
  EXERANY2 VARCHAR(10),
  CVDINFR4 VARCHAR(10),
  CVDCRHD4 VARCHAR(10),
  CVDSTRK3 VARCHAR(10),
  _ASTHMS1 VARCHAR(10),
  ADDEPEV3 VARCHAR(10),
  CHCKDNY2 VARCHAR(10),
  DIABETE4 VARCHAR(10),
  DIFFWALK VARCHAR(10),
  _RFSMOK3 VARCHAR(10),
  _RFDRHV9 VARCHAR(10),
  LSATISFY VARCHAR(10),
  _TOTINDA VARCHAR(10),
  _BMI5CAT VARCHAR(10)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/brfss_2024_subset.csv'
INTO TABLE brfss_clean
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

UPDATE brfss_clean
SET _STATE = CASE 
WHEN _STATE = 1 THEN 'Alabama' 
WHEN _STATE = 2 THEN 'Alaska' 
WHEN _STATE = 4 THEN 'Arizona' 
WHEN _STATE = 5 THEN 'Arkansas' 
WHEN _STATE = 6 THEN 'California' 
WHEN _STATE = 8 THEN 'Colorado' 
WHEN _STATE = 9 THEN 'Connecticut' 
WHEN _STATE = 10 THEN 'Delaware' 
WHEN _STATE = 11 THEN 'District of Columbia'
WHEN _STATE = 12 THEN 'Florida' 
WHEN _STATE = 13 THEN 'Georgia' 
WHEN _STATE = 15 THEN 'Hawaii' 
WHEN _STATE = 16 THEN 'Idaho' 
WHEN _STATE = 17 THEN 'Illinois' 
WHEN _STATE = 18 THEN 'Indiana' 
WHEN _STATE = 19 THEN 'Iowa' 
WHEN _STATE = 20 THEN 'Kansas' 
WHEN _STATE = 21 THEN 'Kentucky' 
WHEN _STATE = 22 THEN 'Louisiana' 
WHEN _STATE = 23 THEN 'Maine' 
WHEN _STATE = 24 THEN 'Maryland' 
WHEN _STATE = 25 THEN 'Massachusetts' 
WHEN _STATE = 26 THEN 'Michigan' 
WHEN _STATE = 27 THEN 'Minnesota' 
WHEN _STATE = 28 THEN 'Mississippi' 
WHEN _STATE = 29 THEN 'Missouri' 
WHEN _STATE = 30 THEN 'Montana' 
WHEN _STATE = 31 THEN 'Nebraska' 
WHEN _STATE = 32 THEN 'Nevada' 
WHEN _STATE = 33 THEN 'New Hampshire' 
WHEN _STATE = 34 THEN 'New Jersey' 
WHEN _STATE = 35 THEN 'New Mexico' 
WHEN _STATE = 36 THEN 'New York' 
WHEN _STATE = 37 THEN 'North Carolina' 
WHEN _STATE = 38 THEN 'North Dakota' 
WHEN _STATE = 39 THEN 'Ohio' 
WHEN _STATE = 40 THEN 'Oklahoma' 
WHEN _STATE = 41 THEN 'Oklahoma' 
WHEN _STATE = 42 THEN 'Pennsylvania' 
WHEN _STATE = 44 THEN 'Rhode Island' 
WHEN _STATE = 45 THEN 'South Carolina' 
WHEN _STATE = 46 THEN 'South Dakota' 
WHEN _STATE = 48 THEN 'Texas' 
WHEN _STATE = 49 THEN 'Utah' 
WHEN _STATE = 50 THEN 'Vermont' 
WHEN _STATE = 51 THEN 'Virginia' 
WHEN _STATE = 53 THEN 'Washington' 
WHEN _STATE = 54 THEN 'West Virginia' 
WHEN _STATE = 55 THEN 'Wisconsin' 
WHEN _STATE = 56 THEN 'Wyoming' 
WHEN _STATE = 66 THEN 'Guam' 
WHEN _STATE = 72 THEN 'Puerto Rico' 
WHEN _STATE = 78 THEN 'Virgin Islands' 
ELSE null END;

SET SQL_SAFE_UPDATES = 0;

ALTER TABLE brfss_clean
MODIFY _STATE VARCHAR(30);

ALTER TABLE brfss_clean
MODIFY SEXVAR VARCHAR(6);

UPDATE brfss_clean
SET SEXVAR = CASE
WHEN SEXVAR = 1 THEN 'Male'
WHEN SEXVAR = 2 THEN 'Female'
End;

UPDATE brfss_clean
SET _AGEG5YR = CASE
WHEN _AGEG5YR = 1 THEN '18-24'
WHEN _AGEG5YR = 2 THEN '25-29'
WHEN _AGEG5YR = 3 THEN '30-34'
WHEN _AGEG5YR = 4 THEN '35-39'
WHEN _AGEG5YR = 5 THEN '40-44'
WHEN _AGEG5YR = 6 THEN '45-49'
WHEN _AGEG5YR = 7 THEN '50-54'
WHEN _AGEG5YR = 8 THEN '55-59'
WHEN _AGEG5YR = 9 THEN '60-64'
WHEN _AGEG5YR = 10 THEN '65-69'
WHEN _AGEG5YR = 11 THEN '70-74'
WHEN _AGEG5YR = 12 THEN '75-79'
WHEN _AGEG5YR = 13 THEN '80+'
WHEN _AGEG5YR = 14 THEN 'Missing'
END;

UPDATE brfss_clean
SET WTKG3 = '0'
WHERE WTKG3 REGEXP '[^0-9.]'
   OR WTKG3 = ''
   OR WTKG3 IS NULL;

ALTER TABLE brfss_clean
MODIFY WTKG3 DECIMAL(7,2);

UPDATE brfss_clean
SET WTKG3 = WTKG3 / 100;

UPDATE brfss_clean
SET HTM4 = '0'
WHERE HTM4 REGEXP '[^0-9.]'
OR HTM4 = ''
OR HTM4 IS NULL;

ALTER TABLE brfss_clean
MODIFY HTM4 INT;

ALTER TABLE brfss_clean
MODIFY _IMPRACE VARCHAR(15);

UPDATE brfss_clean
SET _IMPRACE = CASE
WHEN _IMPRACE = 1 THEN 'White'
WHEN _IMPRACE = 2 THEN 'Black'
WHEN _IMPRACE = 3 THEN 'Asian'
WHEN _IMPRACE = 4 THEN 'American Indian'
WHEN _IMPRACE = 5 THEN 'Hispanic'
WHEN _IMPRACE = 6 THEN 'Other'
END;

ALTER TABLE brfss_clean
MODIFY _EDUCAG VARCHAR(50);

UPDATE brfss_clean
SET _EDUCAG = CASE
WHEN _EDUCAG = 1 THEN 'Elementary School'
WHEN _EDUCAG = 2 THEN 'High School'
WHEN _EDUCAG = 3 THEN 'Attended College or Technical School'
WHEN _EDUCAG = 4 THEN 'College'
WHEN _EDUCAG = 9 THEN 'Missing'
END;

ALTER TABLE brfss_clean
MODIFY EMPLOY1 VARCHAR(50);

UPDATE brfss_clean
SET EMPLOY1 = CASE
WHEN EMPLOY1 = 1 THEN 'Employed'
WHEN EMPLOY1 = 2 THEN 'Self-employed'
WHEN EMPLOY1 = 3 THEN 'Unemployed 1 year+'
WHEN EMPLOY1 = 4 THEN 'Unemployed less then 1 year'
WHEN EMPLOY1 = 5 THEN 'Homemaker'
WHEN EMPLOY1 = 6 THEN 'Student'
WHEN EMPLOY1 = 7 THEN 'Retired'
WHEN EMPLOY1 = 8 THEN 'Unable to work'
WHEN EMPLOY1 = 9 THEN 'Refused'
WHEN EMPLOY1 = NULL THEN 'Missing'
END;

UPDATE brfss_clean
SET EMPLOY1 = 'Missing'
WHERE EMPLOY1 = ''
OR EMPLOY1 IS NULL;

ALTER TABLE brfss_clean
MODIFY _INCOMG1 VARCHAR(20);

UPDATE brfss_clean
SET _INCOMG1 = CASE
WHEN _INCOMG1 = 1 THEN '< $15,000'
WHEN _INCOMG1 = 2 THEN '$15,000 - $25,000'
WHEN _INCOMG1 = 3 THEN '$25,000 - $30,000'
WHEN _INCOMG1 = 4 THEN '$35,000 - $50,000'
WHEN _INCOMG1 = 5 THEN '$50,000 - $100,000'
WHEN _INCOMG1 = 6 THEN '$100,000 - $200,000'
WHEN _INCOMG1 = 7 THEN '> $200,000'
WHEN _INCOMG1 = 9 THEN 'Missing'
END;

UPDATE brfss_clean
SET GENHLTH = CASE
WHEN GENHLTH = 1 THEN 'Excellent'
WHEN GENHLTH = 2 THEN 'Very Good'
WHEN GENHLTH = 3 THEN 'Good'
WHEN GENHLTH = 4 THEN 'Fair'
WHEN GENHLTH = 5 THEN 'Poor'
WHEN GENHLTH = 7 THEN 'Not sure'
WHEN GENHLTH = 9 THEN 'Refused'
WHEN GENHLTH IS NULL THEN 'Missing'
END;


UPDATE brfss_clean
SET MEDCOST1 = CASE
WHEN MEDCOST1 = 1 THEN 'Yes'
WHEN MEDCOST1 = 2 THEN 'No'
WHEN MEDCOST1 = 7 THEN 'Not sure'
WHEN MEDCOST1 = 9 THEN 'Refused'
WHEN MEDCOST1 IS NULL THEN 'Missing'
End;

UPDATE brfss_clean
SET EXERANY2 = CASE
WHEN EXERANY2 = 1 THEN 'Yes'
WHEN EXERANY2 = 2 THEN 'No'
WHEN EXERANY2 = 7 THEN 'Not Sure'
WHEN EXERANY2 = 9 THEN 'Refused'
WHEN EXERANY2 IS NULL THEN 'Missing'
END;

UPDATE brfss_clean
SET CVDINFR4 = CASE
WHEN CVDINFR4 = 1 THEN 'Yes'
WHEN CVDINFR4 = 2 THEN 'No'
WHEN CVDINFR4 = 7 THEN 'Not Sure'
WHEN CVDINFR4 = 9 THEN 'Refused'
WHEN CVDINFR4 IS NULL THEN 'Missing'
END;

UPDATE brfss_clean
SET CVDCRHD4 = CASE
WHEN CVDCRHD4 = 1 THEN 'Yes'
WHEN CVDCRHD4 = 2 THEN 'No'
WHEN CVDCRHD4 = 7 THEN 'Not Sure'
WHEN CVDCRHD4 = 9 THEN 'Refused'
WHEN CVDCRHD4 IS NULL THEN 'Missing'
END;

UPDATE brfss_clean
SET CVDSTRK3 = CASE
WHEN CVDSTRK3 = 1 THEN 'Yes'
WHEN CVDSTRK3 = 2 THEN 'No'
WHEN CVDSTRK3 = 7 THEN 'Not Sure'
WHEN CVDSTRK3 = 9 THEN 'Refused'
WHEN CVDSTRK3 IS NULL THEN 'Missing'
END;

ALTER TABLE brfss_clean
MODIFY _ASTHMS1 VARCHAR(20);

UPDATE brfss_clean
SET _ASTHMS1 = CASE
WHEN _ASTHMS1 = 1 THEN 'Current'
WHEN _ASTHMS1 = 2 THEN 'Former'
WHEN _ASTHMS1 = 3 THEN 'Never'
WHEN _ASTHMS1 = 9 THEN 'Not Sure/Missing'
END;

UPDATE brfss_clean
SET ADDEPEV3 = CASE
WHEN ADDEPEV3 = 1 THEN 'Yes'
WHEN ADDEPEV3 = 2 THEN 'No'
WHEN ADDEPEV3 = 7 THEN 'Not Sure'
WHEN ADDEPEV3 = 9 THEN 'Refused'
WHEN ADDEPEV3 IS NULL THEN 'Missing'
END;

UPDATE brfss_clean
SET CHCKDNY2 = CASE
WHEN CHCKDNY2 = 1 THEN 'Yes'
WHEN CHCKDNY2 = 2 THEN 'No'
WHEN CHCKDNY2 = 7 THEN 'Not Sure'
WHEN CHCKDNY2 = 9 THEN 'Refused'
WHEN CHCKDNY2 IS NULL THEN 'Missing'
END;

ALTER TABLE brfss_clean
MODIFY DIABETE4 VARCHAR(15);

UPDATE brfss_clean
SET DIABETE4 = CASE
WHEN DIABETE4 = 1 THEN 'Yes'
WHEN DIABETE4 = 2 THEN 'No'
WHEN DIABETE4 = 3 THEN 'No'
WHEN DIABETE4 = 4 THEN 'Pre-diabetes'
WHEN DIABETE4 = 7 THEN 'Not sure'
WHEN DIABETE4 = 9 THEN 'Refused' 
WHEN DIABETE4 IS NULL THEN 'Missing'
END;

UPDATE brfss_clean
SET DIFFWALK = CASE
WHEN DIFFWALK = 1 THEN 'Yes'
WHEN DIFFWALK = 2 THEN 'No'
WHEN DIFFWALK = 7 THEN 'Not Sure'
WHEN DIFFWALK = 9 THEN 'Refused'
WHEN DIFFWALK IS NULL THEN 'Missing'
END;

UPDATE brfss_clean
SET _RFSMOK3 = CASE
WHEN _RFSMOK3 = 1 THEN 'No'
WHEN _RFSMOK3 = 2 THEN 'Yes'
WHEN _RFSMOK3 = 9 THEN 'Refused'
END;

UPDATE brfss_clean
SET _RFDRHV9 = CASE
WHEN _RFDRHV9 = 1 THEN 'No'
WHEN _RFDRHV9 = 2 THEN 'Yes'
WHEN _RFDRHV9 = 9 THEN 'Refused'
END;

ALTER TABLE brfss_clean
MODIFY LSATISFY VARCHAR(20);

UPDATE brfss_clean
SET LSATISFY = CASE
WHEN LSATISFY = 1 THEN 'Very satisfied'
WHEN LSATISFY = 2 THEN 'Satisfied'
WHEN LSATISFY = 3 THEN 'Dissatisfied'
WHEN LSATISFY = 4 THEN 'Very dissatisfied'
WHEN LSATISFY = 7 THEN 'Not Sure'
WHEN LSATISFY = 9 THEN 'Not Sure'
WHEN LSATISFY IS NULL THEN 'Missing'
END;

UPDATE brfss_clean
SET _TOTINDA = CASE
WHEN _TOTINDA = 1 THEN 'Yes'
WHEN _TOTINDA = 2 THEN 'No'
WHEN _TOTINDA = 9 THEN 'Missing'
END;

ALTER TABLE brfss_clean
MODIFY _BMI5CAT VARCHAR(15);

UPDATE brfss_clean
SET _BMI5CAT = CASE
WHEN _BMI5CAT = 1 THEN 'Underweight'
WHEN _BMI5CAT = 2 THEN 'Normal Weight'
WHEN _BMI5CAT = 3 THEN 'Overweight'
WHEN _BMI5CAT = 4 THEN 'Obese'
WHEN _BMI5CAT IS NULL THEN 'Missing'
END;

ALTER TABLE brfss_clean
MODIFY PHYSHLTH VARCHAR(15);

UPDATE brfss_clean
SET PHYSHLTH = CASE
WHEN PHYSHLTH = 88 THEN 'None'
WHEN PHYSHLTH BETWEEN 1 AND 7 THEN '1 week or less'
WHEN PHYSHLTH BETWEEN 8 AND 14 THEN '1-2 weeks'
WHEN PHYSHLTH BETWEEN 15 AND 30 THEN '2-4 weeks'
WHEN PHYSHLTH = 77 THEN 'Not sure'
WHEN PHYSHLTH = 99 THEN 'Not sure'
WHEN PHYSHLTH IS NULL THEN 'Missing'
END;

ALTER TABLE brfss_clean
MODIFY MENTHLTH VARCHAR(15);

UPDATE brfss_clean
SET MENTHLTH = CASE
WHEN MENTHLTH = 88 THEN 'None'
WHEN MENTHLTH BETWEEN 1 AND 7 THEN '1 week or less'
WHEN MENTHLTH BETWEEN 8 AND 14 THEN '1-2 weeks'
WHEN MENTHLTH BETWEEN 15 AND 30 THEN '2-4 weeks'
WHEN MENTHLTH = 77 THEN 'Not sure'
WHEN MENTHLTH = 99 THEN 'Not sure'
WHEN MENTHLTH IS NULL THEN 'Missing'
END;

ALTER TABLE brfss_clean
RENAME COLUMN SEQNO TO id,
RENAME COLUMN _STATE TO state,
RENAME COLUMN SEXVAR TO gender,
RENAME COLUMN _AGEG5YR TO age_group,
RENAME COLUMN WTKG3 TO weight,
RENAME COLUMN HTM4 TO height,
RENAME COLUMN _IMPRACE TO race,
RENAME COLUMN _EDUCAG TO education,
RENAME COLUMN EMPLOY1 TO employment,
RENAME COLUMN _INCOMG1 TO income_group,
RENAME COLUMN GENHLTH TO general_health,
RENAME COLUMN PHYSHLTH TO physical_health,
RENAME COLUMN MENTHLTH TO mental_health,
RENAME COLUMN MEDCOST1 TO medical_cost_problem,
RENAME COLUMN EXERANY2 TO exercise,
RENAME COLUMN CVDINFR4 TO heart_attack,
RENAME COLUMN CVDCRHD4 TO coronary_heart_disease,
RENAME COLUMN CVDSTRK3 TO stroke,
RENAME COLUMN _ASTHMS1 TO asthma,
RENAME COLUMN ADDEPEV3 TO depression,
RENAME COLUMN CHCKDNY2 TO kidney_disease,
RENAME COLUMN DIABETE4 TO diabetes,
RENAME COLUMN DIFFWALK TO walking_difficulty,
RENAME COLUMN _RFSMOK3 TO smoking,
RENAME COLUMN _RFDRHV9 TO drinking,
RENAME COLUMN LSATISFY TO life_satisfaction,
RENAME COLUMN _TOTINDA TO physical_activity,
RENAME COLUMN _BMI5CAT TO bmi_category;

UPDATE brfss_clean
SET bmi_category = 'Missing'
WHERE bmi_category IS NULL;

UPDATE brfss_clean
SET life_satisfaction = 'Missing'
WHERE life_satisfaction IS NULL;

UPDATE brfss_clean
SET walking_difficulty = 'Missing'
WHERE walking_difficulty IS NULL;
SELECT * FROM brfss_clean;